# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicebinding',
            options={'permissions': (('gen_binding_code', 'can generate binding code'), ('exe_admin', 'can exe device admin'))},
        ),
    ]
