# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='未分配片区', max_length=32, verbose_name='片区')),
                ('mark', models.CharField(default='', editable=False, max_length=64, verbose_name='层级识别')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='underling', to='account.Dealer', verbose_name='上级代理商')),
            ],
            options={
                'ordering': ['tenant'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['tenant'],
                'permissions': (('view_staff', 'can view staff'),),
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, default='', max_length=128, verbose_name='主页')),
                ('is_cloud_super', models.BooleanField(default=False, verbose_name='超级后台')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_tenant', 'can view tenant'),),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait', models.CharField(blank=True, default='', max_length=256, verbose_name='头像')),
                ('nickname', models.CharField(blank=True, default='', max_length=32, verbose_name='昵称')),
                ('addr', models.CharField(blank=True, default='', max_length=64, verbose_name='地址')),
                ('phone', models.CharField(blank=True, default='', max_length=16, verbose_name='电话')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('S', '保密')], default='S', max_length=2, verbose_name='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('login_admin_site', 'can login admin site'), ('login_app_site', 'can login app site'), ('view_user', 'can view user')),
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='名称')),
                ('type', models.CharField(blank=True, choices=[('T', '第三方'), ('U', '终端用户'), ('S', '云平台')], default='T', max_length=2, verbose_name='类型')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='role', to='auth.Group')),
            ],
            options={
                'ordering': ['type'],
                'permissions': (('view_role', 'can view role'),),
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='roles',
            field=models.ManyToManyField(related_name='staffs', to='account.UserRole'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='account.Tenant'),
        ),
        migrations.AddField(
            model_name='staff',
            name='userself',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userself', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='account.Tenant'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='userself',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
