# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='授权时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='备注'),
        ),
    ]
