# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 16:40
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180306_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(default=account.models.get_app_id, max_length=32, unique=True, verbose_name='appID')),
                ('secret', models.CharField(max_length=32, verbose_name='appSecret')),
                ('nameCN', models.CharField(max_length=32, verbose_name='应用名称')),
                ('nameEN', models.CharField(blank=True, default='', max_length=32, verbose_name='英文名称')),
                ('briefCN', models.CharField(blank=True, default='', max_length=128, verbose_name='应用描述')),
                ('briefEN', models.CharField(blank=True, default='', max_length=128, verbose_name='英文描述')),
                ('site', models.CharField(blank=True, default='', max_length=128, verbose_name='应用官网')),
                ('icon', models.ImageField(default='', editable=False, max_length=200, upload_to=account.models.upload_to_icon)),
                ('icon_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Icon更新日期')),
                ('iosCert', models.ImageField(default='', editable=False, max_length=200, upload_to=account.models.upload_to_cert)),
                ('iosCert_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='key更新日期')),
                ('bundleId', models.CharField(default='', max_length=64, null=True, verbose_name='bundleId')),
                ('wxAppId', models.CharField(default='', max_length=64, null=True, verbose_name='wxAppId')),
                ('wxAppSecret', models.CharField(default='', max_length=64, null=True, verbose_name='wxAppSecret')),
                ('wxAppDefPwd', models.CharField(default='', max_length=64, null=True, verbose_name='wxAppDefPwd')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='account.Application'),
        ),
    ]
