# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180410_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
    ]
