# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 11:37
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180413_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='adv',
            field=models.ImageField(default='', editable=False, max_length=200, upload_to=account.models.upload_to_adv),
        ),
        migrations.AddField(
            model_name='application',
            name='adv_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='广告更新日期'),
        ),
    ]
