# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180504_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='wxAppType',
            field=models.CharField(choices=[('APP', '移动应用'), ('PUB', '公众账号')], default='APP', max_length=4, verbose_name='wxAppType'),
        ),
    ]
