# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 14:12
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_application_wxapptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='h5',
            field=models.FileField(default='', editable=False, max_length=200, upload_to=account.models.upload_to_h5),
        ),
        migrations.AddField(
            model_name='application',
            name='h5_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='H5更新日期'),
        ),
    ]
