# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180508_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='account.Application'),
        ),
    ]
