# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 10:56
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180510_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default='', editable=False, max_length=200, upload_to=account.models.upload_to_avatar),
        ),
    ]
