# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 15:42
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userprofile_avatar_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='', editable=False, max_length=200, upload_to=account.models.upload_to_avatar),
        ),
    ]
