# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_auto_20180508_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, null=True, unique=True, verbose_name='客户代码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='客户名称')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
        ),
        migrations.CreateModel(
            name='HisenseCode',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=14, verbose_name='产品型号编码')),
                ('product', models.CharField(max_length=32, verbose_name='产品型号名称')),
                ('vcode', models.CharField(max_length=2, verbose_name='模块厂商编码')),
                ('vendor', models.CharField(max_length=32, verbose_name='模块厂商名称')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('doer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='account.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='MacSection',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('oui', models.CharField(max_length=6, verbose_name='组织唯一标志符')),
                ('start', models.CharField(max_length=6, verbose_name='号段起始')),
                ('end', models.CharField(max_length=6, verbose_name='号段结束')),
                ('now', models.CharField(max_length=6, verbose_name='当前待分配')),
                ('memo', models.CharField(max_length=32, verbose_name='备注')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('doer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_sections', to='account.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=32, verbose_name='订单说明')),
                ('code_start', models.CharField(max_length=64, null=True, verbose_name='条码起始')),
                ('code_end', models.CharField(max_length=64, null=True, verbose_name='条码结束')),
                ('mac_start', models.CharField(max_length=12, null=True, verbose_name='MAC起始')),
                ('mac_end', models.CharField(max_length=12, null=True, verbose_name='MAC结束')),
                ('count', models.IntegerField(verbose_name='订单数量')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单日期')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='manufacture.Customer')),
                ('doer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.Staff')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='macsection',
            unique_together=set([('oui', 'start', 'end')]),
        ),
        migrations.AlterUniqueTogether(
            name='hisensecode',
            unique_together=set([('pcode', 'vcode')]),
        ),
    ]
