# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_auto_20180308_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='device.Device'),
        ),
    ]
