# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0003_auto_20180323_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timing', to='device.Device'),
        ),
    ]
