# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20180320_0917'),
        ('scene', '0004_auto_20180328_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('device', 'scene')]),
        ),
    ]
