# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180306_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='h5',
            field=models.FileField(default='', editable=False, max_length=200, upload_to=product.models.upload_to_h5),
        ),
        migrations.AddField(
            model_name='product',
            name='h5_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='H5更新日期'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='', editable=False, max_length=200, upload_to=product.models.upload_to_icon),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Icon更新日期'),
        ),
        migrations.AddField(
            model_name='product',
            name='lua',
            field=models.FileField(default='', editable=False, max_length=200, upload_to=product.models.upload_to_lua),
        ),
        migrations.AddField(
            model_name='product',
            name='lua_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Lua更新日期'),
        ),
    ]
