# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180313_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notice', '提醒'), ('alarm', '警报')], max_length=16, verbose_name='消息类型')),
                ('value', models.CharField(max_length=16, verbose_name='属性值')),
                ('msg', models.CharField(max_length=64, verbose_name='消息')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='product.ProductCapability')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='product.Product')),
            ],
        ),
    ]
