# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(help_text='每隔多久记录一次数据(10~86400s)', verbose_name='间隔')),
                ('duration', models.IntegerField(verbose_name='最长时间')),
                ('capability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='product.ProductCapability')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='product.Product')),
            ],
        ),
    ]
