# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_historyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='maximum',
            field=models.IntegerField(default=10000, help_text='与最长保留时间互斥', verbose_name='最多保留记录数'),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='duration',
            field=models.IntegerField(default=31536000, help_text='与最长保留记录数互斥', verbose_name='最长保留时间'),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='interval',
            field=models.IntegerField(default=3600, help_text='每隔多久记录一次数据(10~86400s)', verbose_name='间隔'),
        ),
    ]
