# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180321_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='share',
            field=models.FileField(default='', editable=False, max_length=200, upload_to=product.models.upload_to_h5_share),
        ),
        migrations.AddField(
            model_name='product',
            name='share_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='历史数据分享更新日期'),
        ),
    ]
