# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180327_0857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('product', 'capability', 'value')]),
        ),
    ]
