# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180419_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firmware',
            field=models.ImageField(default='', editable=False, max_length=200, upload_to=product.models.upload_to_firmware),
        ),
        migrations.AddField(
            model_name='product',
            name='firmware_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='固件更新日期'),
        ),
        migrations.AddField(
            model_name='product',
            name='upgrade_cmd',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='升级指令'),
        ),
        migrations.AddField(
            model_name='product',
            name='upgrade_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='升级启动日期'),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='固件版本'),
        ),
    ]
