# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20180524_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='firmware',
            field=models.FileField(default='', editable=False, max_length=200, upload_to=product.models.upload_to_firmware),
        ),
    ]
