# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20180601_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='interval',
            field=models.IntegerField(default=1800, help_text='单位:秒', verbose_name='消息间隔'),
        ),
        migrations.AddField(
            model_name='message',
            name='md5',
            field=models.CharField(default='0123', max_length=4, verbose_name='消息MD5'),
        ),
    ]
