# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='协议名称')),
                ('version', models.CharField(default='1.0.0', max_length=8, verbose_name='版本')),
                ('status', models.CharField(choices=[('active', '最新版'), ('archived', '已归档')], default='active', max_length=16, null=True, verbose_name='状态')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('content', models.TextField(max_length=65536, verbose_name='协议内容')),
            ],
            options={
                'ordering': ['status', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '签约中'), ('auditing', '审核中'), ('approved', '已签约'), ('rejected', '已退回')], default='new', max_length=16, verbose_name='签约状态')),
                ('initiation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发起日期')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效日期')),
                ('effective_to', models.DateTimeField(default=django.utils.timezone.now, verbose_name='合作截止日期')),
                ('contact', models.CharField(max_length=16, verbose_name='申请联系人')),
                ('phone', models.CharField(max_length=16, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('product_category', models.CharField(choices=[('Large', '大家电 如：空调、冰箱、洗衣机、油烟机等等'), ('Small', '小家电 如：空气净化器、电饭煲、烤箱等等'), ('Decoration', '家居家装 如：插座、灯、摄像头、门、锁等等'), ('Entertainment', '数码娱乐 如：音箱、投影仪、电视盒子等等'), ('Wearable', '运动穿戴 如：手环、跑鞋、眼镜等等'), ('Healthy', '健康医疗 如：血压计、血糖仪、体重秤等等'), ('Network', '网络设备 如：路由器、中继器等等'), ('Others', '其他...')], default='Others', max_length=64, null=True, verbose_name='产品类型')),
                ('product_brief', models.CharField(max_length=64, null=True, verbose_name='产品描述')),
                ('memo', models.CharField(blank=True, default='', max_length=64, verbose_name='备注')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followed_contracts', to='contract.Agreement')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audited_contracts', to='account.Staff')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_contracts', to='account.Staff')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='account.Tenant')),
            ],
            options={
                'ordering': ['-update_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together=set([('name', 'status'), ('name', 'version')]),
        ),
    ]
